### ISSUE TITLE
Race conditions in src/main/kotlin/com/faforever/ice/telemetry/GameService.kt

### ISSUE THREAD

**Issue by chathaway-codes** [FAForever/faf-telemetry-server#32]
Hi there,

I'm not an expert in Kotlin or your codebase, but glancing at it I think there is a high probability of a race conditions in src/main/kotlin/com/faforever/ice/telemetry/GameService.kt; a ConcurrentHashMap is used to ensure that we can access the hashmap safely, but the retrieved object is never locked. Additionally, there is no atomocity when adding a new game, which means that if two games had the same ID one would get lost. Not sure if there is possible.

Time permitting, I'll try to write a test to demonstrate this, but it'll take me some time since I haven't used Java/Kotlin in ages.

**Comment by Sheikah45** [comment]
Just wanted to say that two games will never have the same IDs. The game IDs are defined by another service which guarantees unique IDs for each game.

**Comment by chathaway-codes** [comment]
That makes sense. Are there any mechanisms which prevent me from lying and making up my own ID? I don't know how this system works; maybe its gated behind some sort of system which validates the client is telling the truth.

**Comment by Brutus5000** [comment]
There is no security involved. In theory each client could lie about its games and falsely launching games, blocking it to be created then by the actual host.
Not sure what the benefit would be here, because this is just collecting telemetry. Attacking this service would annoy us, but bring no further harm to the overall system.

Nevertheless the ConcurrentHashMap was poor mans implementation before I put this in a more persistent solution. This is not yet defined though.
